name: PR Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  # PR Title and Description Check
  pr-validation:
    runs-on: ubuntu-latest
    name: PR Validation
    
    steps:
      - name: Check PR title format
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            chore
            ci
          requireScope: false
          subjectPattern: ^.{1,72}$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            didn't match the configured pattern. Please ensure that the subject
            doesn't start with an uppercase character and is not longer than 72 characters.

  # Check for breaking changes
  breaking-changes:
    runs-on: ubuntu-latest
    name: Breaking Changes Check
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check for API breaking changes
        run: |
          # Check if there are changes to API routes
          if git diff --name-only HEAD^ HEAD | grep -E "src/app/api|pages/api"; then
            echo "⚠️ API changes detected. Please ensure backward compatibility."
            echo "api-changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Check for database schema changes
        run: |
          # Check if there are changes to Prisma schema
          if git diff --name-only HEAD^ HEAD | grep -E "prisma/schema.prisma"; then
            echo "⚠️ Database schema changes detected. Please ensure migration compatibility."
            echo "schema-changes=true" >> $GITHUB_OUTPUT
          fi

  # Size Impact Check
  bundle-size:
    runs-on: ubuntu-latest
    name: Bundle Size Impact
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Setup build environment
        run: |
          touch .env.production
          echo "DATABASE_URL=file:./build.db" >> .env.production
          echo "AUTH_SECRET=build-secret-key-minimum-32-chars" >> .env.production
          echo "NEXTAUTH_SECRET=build-nextauth-secret-minimum-32-chars" >> .env.production
          echo "NEXTAUTH_URL=http://localhost:3000" >> .env.production
          echo "STRIPE_SECRET_KEY=sk_test_dummy_key_for_build" >> .env.production
          echo "NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_test_dummy_key_for_build" >> .env.production
          echo "STRIPE_WEBHOOK_SECRET=whsec_dummy_key_for_build" >> .env.production
          echo "UPSTASH_REDIS_REST_URL=https://dummy-redis-rest-url.upstash.io" >> .env.production
          echo "UPSTASH_REDIS_REST_TOKEN=dummy_token_for_build" >> .env.production
          echo "FROM_EMAIL=build@example.com" >> .env.production
          echo "RESEND_API_KEY=build_resend_api_key" >> .env.production
          echo "AWS_ACCESS_KEY_ID=build_aws_access_key" >> .env.production
          echo "AWS_SECRET_ACCESS_KEY=build_aws_secret_key" >> .env.production
          echo "AWS_REGION=us-east-1" >> .env.production
          echo "S3_USER_BUCKET=build-bucket" >> .env.production
          echo "NEXT_PUBLIC_CLOUDFRONT_PUBLIC_URL=https://build.cloudfront.net" >> .env.production

      - name: Generate Prisma client
        run: npx prisma generate --schema=prisma/schema.ci.prisma

      - name: Build and analyze bundle
        run: NODE_ENV=production npm run analyze
        env:
          SKIP_ENV_VALIDATION: true
          RATE_LIMIT_ENABLED: false

      - name: Comment bundle size
        uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build_script: build

  # Lighthouse Performance Check
  lighthouse:
    runs-on: ubuntu-latest
    name: Lighthouse Performance Check
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Setup test environment
        run: |
          touch .env.test
          echo "APP_URL=http://localhost:3000" >> .env.test
          echo "DATABASE_URL=file:./test.db" >> .env.test
          echo "AUTH_SECRET=test-secret-key-minimum-32-chars" >> .env.test
          echo "NEXTAUTH_SECRET=test-nextauth-secret-minimum-32-chars" >> .env.test
          echo "NEXTAUTH_URL=http://localhost:3000" >> .env.test
          echo "STRIPE_SECRET_KEY=sk_test_dummy_key_for_lighthouse" >> .env.test
          echo "NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_test_dummy_key_for_lighthouse" >> .env.test
          echo "STRIPE_WEBHOOK_SECRET=whsec_dummy_key_for_lighthouse" >> .env.test
          echo "UPSTASH_REDIS_REST_URL=https://dummy-redis-rest-url.upstash.io" >> .env.test
          echo "UPSTASH_REDIS_REST_TOKEN=dummy_token_for_lighthouse" >> .env.test
          echo "FROM_EMAIL=lighthouse@example.com" >> .env.test
          echo "RESEND_API_KEY=lighthouse_resend_api_key" >> .env.test
          echo "AWS_ACCESS_KEY_ID=lighthouse_aws_access_key" >> .env.test
          echo "AWS_SECRET_ACCESS_KEY=lighthouse_aws_secret_key" >> .env.test
          echo "AWS_REGION=us-east-1" >> .env.test
          echo "S3_USER_BUCKET=lighthouse-bucket" >> .env.test
          echo "NEXT_PUBLIC_CLOUDFRONT_PUBLIC_URL=https://lighthouse.cloudfront.net" >> .env.test
          echo "RATE_LIMIT_ENABLED=false" >> .env.test

      - name: Generate Prisma client and setup database
        run: |
          npx prisma generate --schema=prisma/schema.ci.prisma
          npx prisma db push --schema=prisma/schema.ci.prisma

      - name: Build and start application
        run: |
          NODE_ENV=production npm run build
          npm start &
          sleep 30 # Wait for app to start
        env:
          SKIP_ENV_VALIDATION: true
          RATE_LIMIT_ENABLED: false

      - name: Run Lighthouse
        uses: treosh/lighthouse-ci-action@v10
        with:
          urls: |
            http://localhost:3000
            http://localhost:3000/products
          configPath: './.lighthouserc.json'
          uploadArtifacts: true
          temporaryPublicStorage: true